export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'

export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const GET_SINGLE_PRODUCT_SUCCESS= 'GET_SINGLE_PRODUCT_SUCCESS'
export const GET_SINGLE_PRODUCT_FAILIURE = 'GET_SINGLE_PRODUCT_FAILIURE'

export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILED = 'GET_USER_DATA_FAILED'

export const GET_SINGLE_USER_DATA = 'GET_SINGLE_USER_DATA'
export const GET_SINGLE_USER_DATA_SUCCESS = 'GET_SINGLE_USER_DATA_SUCCESS'
export const GET_SINGLE_USER_DATA_FAILURE = 'GET_SINGLE_USER_DATA_FAILURE'

export const UPDATE_USER_DATA = 'UPDATE_USER_DATA'
export const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS'
export const UPDATE_USER_DATA_FAILURE = 'UPDATE_USER_DATA_FAILURE'

export const USER_DELETE = 'USER_DELETE'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAILIURE = 'USER_DELETE_FAILIURE'

export const ADDING_TO_CART = 'ADDING_TO_CART'
export const ADDING_TO_CART_SUCCESS = 'ADDING_TO_CART_SUCCESS'
export const ADDING_TO_CART_FAILIURE = 'ADDING_TO_CART_FAILIURE'


